# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-21 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='password',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
