# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-23 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20190520_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='workout.Trainer'),
        ),
    ]
