# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-23 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20190523_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='workout_day',
        ),
        migrations.AddField(
            model_name='workout_day',
            name='workouts',
            field=models.ManyToManyField(related_name='workouts', to='workout.Workout'),
        ),
        migrations.AlterField(
            model_name='workout_day',
            name='day',
            field=models.CharField(max_length=10),
        ),
    ]
