# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-28 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_auto_20190523_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='zip',
            field=models.IntegerField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='zip',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name_of_workout',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
