# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-28 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_auto_20190528_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='zip',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='zip',
            field=models.CharField(max_length=5),
        ),
    ]
